### ISSUE TITLE
set up Jekyll

### ISSUE THREAD

**Issue by oschulte** [relational-learning/relational-learning.github.io#2]
Or something equivalent for markdown, Math, and templates

Can we just use "Theme Chooser" in Settings?

**Comment by oschulte** [comment]
Maybe install [Poole](http://getpoole.com/) to get going? I'm having trouble compiling Jekyll.

**Comment by zeruniverse** [comment]
Oops I didn't notice this issue. Will take a look tonight

**Comment by zeruniverse** [comment]
Seems to me theme chooser only works for single page website. I can show
you how to do things if you have time tmr

**Comment by zeruniverse** [comment]
You don't need to install anything, GitHub can compile the site for you. A
web browser is all you need

**Comment by oschulte** [comment]
I think I got it now, thanks!

**Comment by oschulte** [comment]
Hi Jeffrey,

I’ll look for you in the lab. I think I got it but it would be good to double-check. Probably be free around 2 pm if that works for you.

Cheers,

Oliver

-----------------------------------------------------------------------------------------------------

Oliver Schulte					E-mail: oschulte@cs.sfu.ca
Simon Fraser University			Phone: (778) 782-3390
Professor						Fax: (778) 782-3045
School of Computing Science		Web: http://www.cs.sfu.ca/~oschulte
TASC Building	9021			Work Schedule: see home page
Burnaby, B.C. V5A 1S6
Canada

**Comment by zeruniverse** [comment]
I'll wait for you at 2pm
